# Site settings
title: BLEKit - Bluetooth Low Energy Kit
email: self@igorsales.ca
description: >
  Develop your own BLE-based gadgets using BLEKit. From a beacon to a
  remote control app, including sensors and data collection widgets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ble-kit.org" # the base hostname & protocol for your site
twitter_username: igorsales
github_username:  igorsales

# Build settings
markdown: kramdown

# Exclude pages bundled in gems
exclude: [bundle, CNAME, Gemfile, Gemfile.lock, params.json]
